# Generated by Django 5.0.4 on 2024-04-05 12:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='عنوان خبر')),
                ('slug', models.SlugField(allow_unicode=True, help_text='نامک آدرس لینک خبر در مرورگر است و باید یکتا باشد.', max_length=255, unique=True, verbose_name='نامک')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('status', models.CharField(choices=[('DF', 'پیش\u200cنویس'), ('PB', 'منتشر شده')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اخبار',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='news_news_publish_632715_idx')],
            },
        ),
    ]
