# Generated by Django 5.0.4 on 2024-04-05 12:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='یکی بود یکی نبود', verbose_name='متن خبر'),
            preserve_default=False,
        ),
    ]
