# Generated by Django 5.0.4 on 2024-04-05 14:22

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=filebrowser.fields.FileBrowseField(default='test', max_length=255, verbose_name='تصویر خبر'),
            preserve_default=False,
        ),
    ]
