# Generated by Django 5.0.4 on 2024-04-04 06:47

import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='نام سایت که در تمامی صفحات نمایش داده می\u200cشود.', max_length=255, verbose_name='نام سایت')),
                ('site_logo', filebrowser.fields.FileBrowseField(help_text='لوگوی سایت که در تمامی صفحات نمایش داده می\u200cشود.', max_length=255, verbose_name='لوگوی سایت')),
                ('site_description_tag', models.CharField(help_text='این تگ به بازدیدکنندگان نمایش داده نشده و فقط برای موتورهای جستجو نظیر گوگل کاربرد دارد. برای اطلاعات بیشتر با متخصص SEO مشورت کنید.', max_length=255, verbose_name='تگ توضیحات سایت')),
                ('homepage_title', models.CharField(help_text='عنوان صفحه اول سایت که به بازدیدکنندگان نمایش داده می\u200cشود.', max_length=255, verbose_name='عنوان صفحه اول')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
