# Generated by Django 5.0.4 on 2024-04-04 07:28

import ckeditor.fields
import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(help_text='عنوان بخش "درباره ما" که در صفحه اول نمایش داده می\u200cشود.', max_length=255, verbose_name='عنوان درباره ما')),
                ('about_description', ckeditor.fields.RichTextField(help_text='متن "درباره ما" که در صفحه اول نمایش داده می\u200cشود.', verbose_name='متن درباره ما')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(help_text='عنوان فعالیت که در بخش "درباره ما" نمایش داده می\u200cشود.', max_length=255, verbose_name='عنوان فعالیت')),
                ('activity_description', ckeditor.fields.RichTextField(help_text='تشریح فعالیت که در بخش "درباره ما" نمایش داده می\u200cشود.', verbose_name='تشریح فعالیت')),
            ],
            options={
                'verbose_name': 'حوزه فعالیت',
                'verbose_name_plural': 'حوزه\u200cهای فعالیت',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', filebrowser.fields.FileBrowseField(help_text='تصویر محصول که در اسلایدر صفحه اول نمایش داده می\u200cشود.', max_length=255, verbose_name='تصویر اسلایدر')),
                ('slide_title', models.CharField(help_text='عنوان اصلی که در اسلایدر صفحه اول نمایش داده می\u200cشود.', max_length=255, verbose_name='عنوان اصلی اسلایدر')),
                ('slide_subtitle', models.CharField(help_text='عنوان فرعی که در اسلایدر صفحه اول نمایش داده می\u200cشود.', max_length=255, verbose_name='عنوان فرعی اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_title', models.CharField(help_text='عنوان آمار که در بخش "آمار" نمایش داده می\u200cشود.', max_length=255, verbose_name='عنوان آمار')),
                ('stat_number', models.IntegerField(help_text='عدد آمار که در بخش "آمار" نمایش داده می\u200cشود.', verbose_name='عدد آمار')),
            ],
            options={
                'verbose_name': 'آمار',
                'verbose_name_plural': 'آمارها',
            },
        ),
    ]
