# Generated by Django 5.0.4 on 2024-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_icon',
            field=models.CharField(blank=True, help_text='آیکون این فعالیت', max_length=50, verbose_name='آیکون'),
        ),
    ]
