# Generated by Django 5.0.4 on 2024-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_activity_activity_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(help_text='نام کارفرمای پروژه', max_length=255, verbose_name='کارفرما')),
                ('description', models.TextField(help_text='جزئیات پروژه', verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
    ]
