# Generated by Django 5.0.4 on 2024-04-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_service_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Project',
        ),
    ]
