# Generated by Django 5.0.4 on 2024-04-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_service_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=models.TextField(help_text='تشریح فعالیت که در بخش "درباره ما" نمایش داده می\u200cشود.', verbose_name='تشریح فعالیت'),
        ),
    ]
