# Generated by Django 5.0.4 on 2024-04-05 12:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_activity_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=ckeditor.fields.RichTextField(help_text='تشریح فعالیت که در بخش "درباره ما" نمایش داده می\u200cشود.', verbose_name='تشریح فعالیت'),
        ),
    ]
